# Raspberry Kitchen Radio — route to the always-available headphone output.
pcm.!default {
    type plug
    slave.pcm "sysdefault:CARD=Headphones"
}

ctl.!default {
    type hw
    card Headphones
}
